runtime: python38
service: backend
entrypoint: gunicorn -b :$PORT main:app --timeout 0
instance_class: F4_1G
env_variables: 
  NLTK_DATA: './nltk_data'
handlers:
# backend
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: staticfavicon.ico

- url: /
  static_files: templates/index.html
  upload: templates/index.html

- url: /.*
  script: auto
